"""Business list scraped from Google search of FB business pages."""

BUSINESSES = [
    # === Surrey BC handymen ===
    {"name":"Surrey Handyman and Renovations","slug":"surrey-handyman","city":"Surrey","state":"BC","phone":"(604) 245-5960","email":"hello@surreyhandyman.example","industry":"handyman","fb":"https://www.facebook.com/surreyhandymanBC/","years":15,"jobs":1200,"primary":"#0F4C81","accent":"#F2A93B"},
    {"name":"604 Handyman","slug":"604-handyman","city":"Delta","state":"BC","phone":"(604) 245-5960","email":"wrss@604handyman.com","industry":"handyman","fb":"https://www.facebook.com/604handyman/","years":12,"jobs":900,"primary":"#1E3A8A","accent":"#FBBF24"},
    {"name":"Ultimate Handyman & Renovations","slug":"ultimate-handyman","city":"Surrey","state":"BC","phone":"(604) 401-9791","email":"info@theultimateconstruction.example","industry":"handyman","fb":"https://www.facebook.com/ultimatehandymanandrenovations/","years":10,"jobs":750,"primary":"#0E7C66","accent":"#E0A800"},
    {"name":"Fixall Handyman Services","slug":"fixall-handyman","city":"Surrey","state":"BC","phone":"(604) 839-0097","email":"fixall604@gmail.com","industry":"handyman","fb":"https://www.facebook.com/fixall604/","years":8,"jobs":600,"primary":"#9A2A2A","accent":"#F4C064"},
    {"name":"Anything Goes Handyman","slug":"anything-goes-handyman","city":"Surrey","state":"BC","phone":"(778) 241-1178","email":"info@anythinggoes.example","industry":"handyman","fb":"https://www.facebook.com/anythinggoeshandyman/","years":7,"jobs":520,"primary":"#1F4E5F","accent":"#F0A040"},
    {"name":"SV Handyman Services","slug":"sv-handyman","city":"Surrey","state":"BC","phone":"(604) 206-2435","email":"info@svhandymanservices.example","industry":"handyman","fb":"https://www.facebook.com/p/SV-Handyman-Services-61568421322724/","years":9,"jobs":680,"primary":"#2C3E50","accent":"#E67E22"},
    {"name":"White Rock Renovations","slug":"white-rock-renovations","city":"South Surrey","state":"BC","phone":"(604) 538-1234","email":"contact@whiterockrenos.example","industry":"handyman","fb":"https://www.facebook.com/whiterockrenovations","years":18,"jobs":1500,"primary":"#34495E","accent":"#F1C40F"},

    # === Surrey BC bakeries ===
    {"name":"Cakes by Kay","slug":"cakes-by-kay","city":"South Surrey","state":"BC","phone":"(604) 555-2010","email":"orders@cakesbykay.example","industry":"bakery","fb":"https://www.facebook.com/cakesbykcg/","years":10,"jobs":2000,"primary":"#C71585","accent":"#FFB6C1"},
    {"name":"Sweet Revenge Bakery & Cafe","slug":"sweet-revenge-bakery","city":"Surrey","state":"BC","phone":"(604) 555-2011","email":"hello@sweetrevenge.example","industry":"bakery","fb":"https://www.facebook.com/p/Sweet-Revenge-Bakery-Cafe-100087937997302/","years":6,"jobs":1500,"primary":"#8B0000","accent":"#FFD700"},
    {"name":"Minute Bakery","slug":"minute-bakery","city":"Surrey","state":"BC","phone":"(604) 555-2012","email":"hello@minutebakery.example","industry":"bakery","fb":"https://www.facebook.com/minutebakery/","years":12,"jobs":3000,"primary":"#A0522D","accent":"#FFE4B5"},
    {"name":"Sweet Avenue Bakery","slug":"sweet-avenue-bakery","city":"Surrey","state":"BC","phone":"(604) 555-2013","email":"contact@sweetavenue.example","industry":"bakery","fb":"https://www.facebook.com/sweetavenuebakery/","years":11,"jobs":2500,"primary":"#D2691E","accent":"#FFDAB9"},
    {"name":"Joyful Indulgence Bakeshop","slug":"joyful-indulgence","city":"Surrey","state":"BC","phone":"(604) 555-2014","email":"hello@joyfulindulgence.example","industry":"bakery","fb":"https://www.facebook.com/JoyfulIndulgenceBakeshop/","years":8,"jobs":1800,"primary":"#9932CC","accent":"#FFE4E1"},
    {"name":"New Amsterdam Bakery","slug":"new-amsterdam-bakery","city":"Surrey","state":"BC","phone":"(604) 555-2015","email":"hello@newamsterdam.example","industry":"bakery","fb":"https://www.facebook.com/newamsterdambakery/","years":15,"jobs":3500,"primary":"#FF6347","accent":"#FFEFD5"},
    {"name":"Cloverdale Bakery","slug":"cloverdale-bakery","city":"Surrey","state":"BC","phone":"(604) 555-2016","email":"hello@cloverdalebakery.example","industry":"bakery","fb":"https://www.facebook.com/Cloverdalebakery/","years":20,"jobs":5000,"primary":"#B8860B","accent":"#FFF8DC"},

    # === Yakima WA food trucks ===
    {"name":"El Quesadillo Food Truck","slug":"el-quesadillo","city":"Yakima","state":"WA","phone":"(509) 307-4372","email":"hello@elquesadillo.example","industry":"food-truck","fb":"https://www.facebook.com/elquesadilloyakima/","years":7,"jobs":15000,"primary":"#C1272D","accent":"#F4C220"},
    {"name":"What I Crave Food Truck","slug":"what-i-crave","city":"Yakima","state":"WA","phone":"(509) 555-3001","email":"hello@whaticrave.example","industry":"food-truck","fb":"https://www.facebook.com/Whaticravefoodtruck/","years":5,"jobs":12000,"primary":"#FF6F00","accent":"#FFE082"},
    {"name":"Don Cheo's Taqueria","slug":"don-cheos","city":"Yakima","state":"WA","phone":"(509) 555-3002","email":"hello@doncheos.example","industry":"food-truck","fb":"https://www.facebook.com/p/Don-Cheos-Taqueria-100083672021552/","years":9,"jobs":18000,"primary":"#A52A2A","accent":"#FFD54F"},
    {"name":"Xochitl's Street Food","slug":"xochitls","city":"Yakima","state":"WA","phone":"(509) 555-3003","email":"hello@xochitls.example","industry":"food-truck","fb":"https://www.facebook.com/MimisEvents509/","years":6,"jobs":11000,"primary":"#B71C1C","accent":"#F9A825"},
    {"name":"CrazyFoods/Chronic","slug":"crazyfoods","city":"Yakima","state":"WA","phone":"(509) 555-3004","email":"hello@crazyfoods.example","industry":"food-truck","fb":"https://www.facebook.com/crazyfoodsofyakima/","years":4,"jobs":9000,"primary":"#1A237E","accent":"#FF4081"},

    # === Yakima WA auto detail ===
    {"name":"Johnson's Mobile Detailing","slug":"johnsons-mobile-detail","city":"Yakima","state":"WA","phone":"(509) 901-4580","email":"johnson@mobiledetail.example","industry":"auto-detail","fb":"https://www.facebook.com/p/Johnsons-Mobile-Detailing-100054356449048/","years":11,"jobs":2400,"primary":"#0D47A1","accent":"#FFC107"},
    {"name":"MudHog Mobile Detailing","slug":"mudhog-detail","city":"Yakima","state":"WA","phone":"(509) 728-5560","email":"hello@mudhog.example","industry":"auto-detail","fb":"https://www.facebook.com/MudHogAutoDetailingandWindowTint/","years":9,"jobs":1900,"primary":"#3E2723","accent":"#FFAB00"},
    {"name":"Pro-Clean Auto Detail","slug":"proclean-detail","city":"Yakima","state":"WA","phone":"(509) 555-4001","email":"hello@proclean.example","industry":"auto-detail","fb":"https://www.facebook.com/ProCleanAutoDetail","years":13,"jobs":3200,"primary":"#1565C0","accent":"#FDD835"},
    {"name":"B & E Auto Detail","slug":"be-auto-detail","city":"Yakima","state":"WA","phone":"(509) 469-4819","email":"hello@beautodetail.example","industry":"auto-detail","fb":"https://www.facebook.com/p/B-E-Auto-Detail-100057588882541/","years":12,"jobs":2700,"primary":"#212121","accent":"#FFD600"},
    {"name":"Exclusive360 Auto Detailing","slug":"exclusive360","city":"Yakima","state":"WA","phone":"(509) 555-4002","email":"hello@exclusive360.example","industry":"auto-detail","fb":"https://www.facebook.com/DRIVEGlassyDRIVEClean/","years":7,"jobs":1500,"primary":"#000000","accent":"#FFD700"},
    {"name":"Silva's Auto Detail","slug":"silvas-auto-detail","city":"Yakima","state":"WA","phone":"(509) 555-4003","email":"hello@silvasdetail.example","industry":"auto-detail","fb":"https://www.facebook.com/SilvasAutoDetail/","years":10,"jobs":2200,"primary":"#1B5E20","accent":"#FFEB3B"},
    {"name":"Mo's Auto Detail","slug":"mos-auto-detail","city":"Terrace Heights","state":"WA","phone":"(509) 555-4004","email":"hello@mosauto.example","industry":"auto-detail","fb":"https://www.facebook.com/moises2066/","years":8,"jobs":1700,"primary":"#4A148C","accent":"#FFCA28"},

    # === Bellingham WA pet ===
    {"name":"Bellingham Dog Walking","slug":"bellingham-dog-walking","city":"Bellingham","state":"WA","phone":"(360) 927-7412","email":"walkmyfluffy@example.com","industry":"pet-grooming","fb":"https://www.facebook.com/walkmyfluffy/","years":8,"jobs":1500,"primary":"#558B2F","accent":"#FFB300"},
    {"name":"Holy ShihTzu Grooming","slug":"holy-shihtzu","city":"Bellingham","state":"WA","phone":"(360) 305-5745","email":"hello@holyshihtzu.example","industry":"pet-grooming","fb":"https://www.facebook.com/p/Holy-ShihTzu-100075122610718/","years":7,"jobs":2200,"primary":"#6A1B9A","accent":"#FFB300"},
    {"name":"Sit & Stroll Pet Care","slug":"sit-and-stroll","city":"Bellingham","state":"WA","phone":"(360) 555-5001","email":"sitandstrollpets@gmail.com","industry":"pet-grooming","fb":"https://www.facebook.com/SitandStrollPets/","years":6,"jobs":1100,"primary":"#0277BD","accent":"#FFA000"},
    {"name":"Shake & Shine LLC","slug":"shake-and-shine","city":"Bellingham","state":"WA","phone":"(360) 555-5002","email":"hello@shakeandshine.example","industry":"pet-grooming","fb":"https://www.facebook.com/ShakeAndShineLLC/","years":5,"jobs":900,"primary":"#283593","accent":"#FFB300"},
    {"name":"City Dogs Bellingham","slug":"city-dogs","city":"Bellingham","state":"WA","phone":"(360) 555-5003","email":"hello@citydogsbham.example","industry":"pet-grooming","fb":"https://www.facebook.com/CityDogsGrooming/","years":28,"jobs":12000,"primary":"#37474F","accent":"#FFC107"},
    {"name":"Bailey's Neighborhood Pet","slug":"baileys-pet","city":"Bellingham","state":"WA","phone":"(360) 733-9274","email":"hello@baileyspet.example","industry":"pet-grooming","fb":"https://www.facebook.com/baileysbath/","years":15,"jobs":4200,"primary":"#5D4037","accent":"#FFA726"},
    {"name":"Poodle Creek Grooming","slug":"poodle-creek","city":"Bellingham","state":"WA","phone":"(360) 555-5004","email":"hello@poodlecreek.example","industry":"pet-grooming","fb":"https://www.facebook.com/poodlecreek/","years":10,"jobs":2800,"primary":"#4527A0","accent":"#FFD54F"},
    {"name":"Shear to Chic Mobile Grooming","slug":"shear-to-chic","city":"Bellingham","state":"WA","phone":"(360) 555-5005","email":"hello@sheartochic.example","industry":"pet-grooming","fb":"https://www.facebook.com/sheartochicgrooming","years":7,"jobs":1400,"primary":"#AD1457","accent":"#FFD180"},

    # === Bellingham WA cleaning ===
    {"name":"Spree Clean of Bellingham","slug":"spree-clean","city":"Bellingham","state":"WA","phone":"(360) 555-6001","email":"hello@spreeclean.example","industry":"cleaning","fb":"https://www.facebook.com/spreeclean","years":9,"jobs":3200,"primary":"#0288D1","accent":"#FFCA28"},
    {"name":"RSK Cleaning Services","slug":"rsk-cleaning","city":"Bellingham","state":"WA","phone":"(360) 555-6002","email":"hello@rskcleaning.example","industry":"cleaning","fb":"https://www.facebook.com/rskcleaning","years":11,"jobs":4100,"primary":"#00838F","accent":"#FFB300"},
    {"name":"Abby's Cleaning Service","slug":"abbys-cleaning","city":"Bellingham","state":"WA","phone":"(360) 555-6003","email":"hello@abbyscleaning.example","industry":"cleaning","fb":"https://www.facebook.com/abbyscleaningsvc","years":13,"jobs":4800,"primary":"#7B1FA2","accent":"#FFD54F"},
    {"name":"Cascade Home Cleaning","slug":"cascade-home-cleaning","city":"Bellingham","state":"WA","phone":"(360) 555-6004","email":"hello@cascadeclean.example","industry":"cleaning","fb":"https://www.facebook.com/cascadehomecleaning","years":14,"jobs":5200,"primary":"#1A5F3E","accent":"#FFC107"},

    # === Yakima WA landscaping ===
    {"name":"Russell Landscaping","slug":"russell-landscaping","city":"Yakima","state":"WA","phone":"(509) 555-7001","email":"hello@russelllandscaping.example","industry":"landscaping","fb":"https://www.facebook.com/russelllandscapingyakima","years":22,"jobs":2400,"primary":"#1B5E20","accent":"#FBC02D"},
    {"name":"Perez Landscaping","slug":"perez-landscaping","city":"Yakima","state":"WA","phone":"(509) 555-7002","email":"hello@perezlandscaping.example","industry":"landscaping","fb":"https://www.facebook.com/perezlandscapingllc","years":20,"jobs":2200,"primary":"#33691E","accent":"#FFB300"},
    {"name":"Absolute Lawn Care","slug":"absolute-lawn-care","city":"Selah","state":"WA","phone":"(509) 555-7003","email":"hello@absolutelawncare.example","industry":"landscaping","fb":"https://www.facebook.com/absolutelawncareyakima","years":17,"jobs":1900,"primary":"#2E7D32","accent":"#FFCA28"},
    {"name":"Rimrock Landscapes","slug":"rimrock-landscapes","city":"Yakima","state":"WA","phone":"(509) 972-7400","email":"hello@rimrocklandscapes.example","industry":"landscaping","fb":"https://www.facebook.com/rimrocklandscapes","years":18,"jobs":2000,"primary":"#3E2723","accent":"#FBC02D"},
    {"name":"VS Landscaping","slug":"vs-landscaping","city":"Yakima","state":"WA","phone":"(509) 555-7004","email":"hello@vslandscaping.example","industry":"landscaping","fb":"https://www.facebook.com/vslandscaping","years":15,"jobs":1700,"primary":"#0F7B3F","accent":"#FFD54F"},

    # === Yakima WA barbers ===
    {"name":"Royalty Barber Studio","slug":"royalty-barber","city":"Yakima","state":"WA","phone":"(509) 555-8001","email":"hello@royaltybarber.example","industry":"barber","fb":"https://www.facebook.com/royaltybarberstudio","years":4,"jobs":3500,"primary":"#1A1A1A","accent":"#D4AF37"},
    {"name":"Top Tier Barbershop","slug":"top-tier-barber","city":"Yakima","state":"WA","phone":"(509) 555-8002","email":"hello@toptierbarber.example","industry":"barber","fb":"https://www.facebook.com/toptierbarberyakima","years":6,"jobs":4800,"primary":"#0A0A0A","accent":"#C9A227"},
    {"name":"Finely Fresh Barbershop","slug":"finely-fresh","city":"Yakima","state":"WA","phone":"(509) 555-8003","email":"hello@finelyfresh.example","industry":"barber","fb":"https://www.facebook.com/finelyfreshbarberspa","years":7,"jobs":5200,"primary":"#3E2723","accent":"#D4A017"},
    {"name":"DC Barbershop","slug":"dc-barbershop","city":"Yakima","state":"WA","phone":"(509) 555-8004","email":"hello@dcbarbershop.example","industry":"barber","fb":"https://www.facebook.com/dcbarbershopyakima","years":9,"jobs":6500,"primary":"#212121","accent":"#FFB300"},
    {"name":"New Chapter Salon & Barber","slug":"new-chapter","city":"Yakima","state":"WA","phone":"(509) 555-8005","email":"hello@newchaptersalon.example","industry":"barber","fb":"https://www.facebook.com/newchapteryakima","years":5,"jobs":3800,"primary":"#311B92","accent":"#F0C040"},
]
