"""Industry-specific copy + Unsplash hero/gallery image IDs."""

INDUSTRIES = {
    "handyman": {
        "title": "Handyman & Renovations",
        "unit": "Jobs",
        "keywords": "handyman, home repair, renovations, drywall, plumbing fixes, electrical, painting",
        "hero_words": ("One call. ", "All fixed."),
        "tagline": "From the busted hinge to the half-finished basement — local handyman that actually shows up, finishes the work, and leaves it cleaner than they found it.",
        "services_intro": "Big jobs, small jobs, anything in between. If it's broken, leaking, sagging, or never got finished — we'll handle it.",
        "services": [
            ("🔧","General Repairs","Door hardware, drywall patching, fence boards, leaky faucets — any odd jobs around the house."),
            ("🔨","Renovations","Bathroom refresh, kitchen update, basement build-out. Licensed & insured for full reno work."),
            ("🪛","TV & Mounting","TV mounts, shelving, art &amp; mirrors, blinds, curtain rods. Studs found right, level every time."),
            ("🪜","Decks &amp; Fences","Deck boards replaced, railings rebuilt, fence sections fixed, gates re-hung."),
            ("🚿","Plumbing Fixes","Faucets, toilets, garbage disposals, p-traps, shower heads, hose bibs. Quick fixes, fair price."),
            ("⚡","Electrical Fixes","Switches, outlets, fixtures, ceiling fans, doorbells. Permits handled when needed."),
        ],
        "reviews": [
            ("Mike was prompt, professional, and finished the work the same day. Fixed my fence gate, replaced two outlets, and re-hung a closet door — quoted me fair and stuck to it.", "K. Wilson", "Local Customer"),
            ("Honestly the only handyman in town who actually answers their phone and shows up when they say. Did a full bathroom refresh for me — flawless work.", "S. Chen", "Repeat Customer"),
            ("Got a quote in an hour, work done by the weekend. Cleaned up perfectly, even vacuumed the dust. Will absolutely call again.", "J. Patel", "Local Customer"),
        ],
        "hero_imgs": ["1581094271901-8022df4466f9","1574359411659-15573a27a8a4","1572116469696-31de0f17cc34"],
        "gallery_imgs": ["1581094271901-8022df4466f9","1572116469696-31de0f17cc34","1581094298634-5a4b2b66ae45","1581094795321-1ee3b1f7f04a","1593093456015-6a5d1c5ae8f4","1576004193264-d97c2cc9d164"],
        "license": "Licensed &amp; Insured",
        "biz_blurb": "We&apos;re a small local crew that takes pride in showing up on time, sweating the details, and leaving the job better than we found it. Free quotes, no pressure, no hidden fees.",
    },
    "bakery": {
        "title": "Artisan Bakery & Cafe",
        "unit": "Custom Orders",
        "keywords": "bakery, cake, pastry, custom cakes, wedding cakes, bread, cafe",
        "hero_words": ("Made fresh. ", "Every morning."),
        "tagline": "Small-batch breads, custom cakes, hand-rolled pastries — baked from scratch with real butter, real flour, no shortcuts.",
        "services_intro": "From a Tuesday-morning croissant to a 4-tier wedding cake, we bake everything in-house every day.",
        "services": [
            ("🎂","Custom Cakes","Birthdays, weddings, baby showers — your design or ours. Tier on tier, custom flavors, no boring buttercream."),
            ("🥐","Daily Pastries","Croissants, pain au chocolat, danishes, scones &amp; muffins. Out of the oven every morning by 7."),
            ("🍞","Artisan Breads","Sourdough, baguette, focaccia, brioche. Same-day fresh or order whole loaves for the week."),
            ("☕","Cafe Drinks","Locally-roasted espresso, drip coffee, hot chocolate &amp; chai. Best paired with a fresh-out-the-oven pastry."),
            ("🧁","Cupcakes &amp; Cookies","Single-serve treats by the dozen. Perfect for offices, parties &amp; thank-you gifts."),
            ("🍪","Catering &amp; Events","Pastry boxes, cake tables, dessert bars for parties, weddings &amp; corporate events."),
        ],
        "reviews": [
            ("Best croissants I&apos;ve had outside of Paris, full stop. Flaky, buttery, perfect crumb. We&apos;re here twice a week now.","M. Thompson","Local Regular"),
            ("Ordered a custom 50th birthday cake for my mom — they nailed the design, flavor was incredible, came in on budget. Going back for every event.","R. Singh","Custom Cake Customer"),
            ("Owner-operated and you can taste it. Real ingredients, real love, real fresh. Best bakery in the neighborhood by a mile.","A. Garcia","Loyal Customer"),
        ],
        "hero_imgs": ["1486427944299-d1955d23e34d","1509440159596-0249088772ff","1517433367423-c7e5b0f35086"],
        "gallery_imgs": ["1486427944299-d1955d23e34d","1509440159596-0249088772ff","1517433367423-c7e5b0f35086","1488477181946-6428a0291777","1565299543923-37dd37887442","1551024506-0bccd828d307"],
        "license": "",
        "biz_blurb": "We&apos;re a family-run bakery that bakes everything from scratch, every morning. Walk in any day for fresh pastries, or order ahead for cakes, breads &amp; catering.",
    },
    "food-truck": {
        "title": "Food Truck",
        "unit": "Orders Served",
        "keywords": "food truck, mexican food, tacos, street food, catering, lunch, dinner",
        "hero_words": ("Real food. ", "On the move."),
        "tagline": "Hand-made tacos, burritos &amp; street food from a family kitchen — fresh-pressed tortillas, slow-braised meats, salsas made from scratch.",
        "services_intro": "Track us around town, book us for your event, or stop by the regular spot. Hot food, fast line, full bellies.",
        "services": [
            ("🌮","Tacos","Carne asada, al pastor, carnitas, chicken &amp; veggie. Hand-pressed corn tortillas, all the salsas."),
            ("🌯","Burritos","Wet, dry, breakfast or anytime. Stuffed full and rolled tight. Add-ons for the brave."),
            ("🍔","Street Eats","Loaded fries, quesadillas, tortas &amp; daily specials. Whatever&apos;s hot off the grill."),
            ("🥤","Drinks","Fresh agua frescas, Mexican Coke in the bottle, horchata, jamaica. Iced or warm."),
            ("🎉","Event Catering","Weddings, corporate, birthdays. We park the truck, you eat all night. Set menus or buffet style."),
            ("📍","Track the Truck","Different spot every day. Find us on Facebook for daily location &amp; menu updates."),
        ],
        "reviews": [
            ("Best tacos in town. Period. Their al pastor with fresh pineapple is the best thing I&apos;ve eaten this year.","E. Rodriguez","Local Regular"),
            ("We hired the truck for our wedding — 120 guests, all fed, line moved fast, food was incredible. Worth every penny.","D. Carter","Event Customer"),
            ("Family-run, fresh tortillas, hot off the grill. I drive 20 minutes out of my way just for their carnitas burritos.","A. Lopez","Repeat Customer"),
        ],
        "hero_imgs": ["1565299585323-38d6b0865b47","1599974579688-8dbdd335c77f","1606756790138-261d2b21cd75"],
        "gallery_imgs": ["1565299585323-38d6b0865b47","1599974579688-8dbdd335c77f","1606756790138-261d2b21cd75","1551881420-ccbb6f69e063","1565299624946-b28f40a0ae38","1551782450-a2132b4ba21d"],
        "license": "",
        "biz_blurb": "We&apos;re a family-run food truck serving real, made-from-scratch street food. Find us around town or book the truck for your event &mdash; weddings, parties, corporate lunches all welcome.",
    },
    "auto-detail": {
        "title": "Mobile Auto Detailing",
        "unit": "Vehicles Detailed",
        "keywords": "auto detailing, mobile detailing, car wash, ceramic coating, paint correction, interior cleaning",
        "hero_words": ("Showroom shine. ","Driveway service."),
        "tagline": "We bring the detail shop to your driveway. Hand wash, paint correction, full interior, ceramic coatings — your car back to better-than-new without you ever leaving home.",
        "services_intro": "Mobile detailing means we come to you. Office parking lot, driveway, garage — we bring the water, power, and product.",
        "services": [
            ("🚗","Full Detail","Hand wash, clay bar, machine polish, full interior shampoo, leather conditioning, glass &amp; trim. 4-6 hours, factory fresh."),
            ("✨","Paint Correction","One-stage or multi-stage cut &amp; polish. Removes swirls, scratches &amp; oxidation. Mirror finish, ceramic-ready."),
            ("💎","Ceramic Coating","Multi-year paint protection. Self-cleaning, hydrophobic, UV-stable. Pro-grade application, written warranty."),
            ("🪟","Window Tint","Premium ceramic or carbon film. Lifetime warranty, legal tint percentages, free in-shop appointments."),
            ("🧽","Interior Detail","Steam clean, vacuum, leather/vinyl/cloth treatment, headliner spot clean, carpet shampoo. Smoke &amp; pet smell removal available."),
            ("🛻","Truck &amp; RV","Lifted trucks, work trucks, RVs &amp; boats. We have the equipment for any size — bring it on."),
        ],
        "reviews": [
            ("My truck looked like it just rolled off the lot. They came to my work, did the full detail in the parking lot in 5 hours, charged exactly what they quoted. Already booked the next one.","T. Anderson","Mobile Detail Customer"),
            ("Got the ceramic coating package on my Tesla — paint pops, water beads off, hasn&apos;t needed a real wash in 6 months. Worth every dollar.","K. Nguyen","Ceramic Customer"),
            ("Paint correction on my older car was unreal — looks 10 years younger. Professional, on-time, and the work speaks for itself.","M. Roberts","Paint Correction Customer"),
        ],
        "hero_imgs": ["1605559424843-9e4c228bf1c2","1492144534655-ae79c964c9d7","1583121274602-3e2820c69888"],
        "gallery_imgs": ["1605559424843-9e4c228bf1c2","1492144534655-ae79c964c9d7","1583121274602-3e2820c69888","1494976388531-d1058494cdd8","1597007030739-6d2e7172ee6a","1552519507-da3b142c6e3d"],
        "license": "Licensed &amp; Insured",
        "biz_blurb": "We&apos;re a mobile detail crew that comes to your driveway, office, or garage with everything we need. Free estimates over text — send a few photos, we&apos;ll quote it back.",
    },
    "pet-grooming": {
        "title": "Pet Grooming &amp; Care",
        "unit": "Happy Pets",
        "keywords": "dog grooming, pet grooming, dog walking, pet sitting, mobile grooming, full service grooming",
        "hero_words": ("Calmer pets. ","Cleaner homes."),
        "tagline": "Full-service grooming and pet care from people who actually like your dog. Quiet salon, breed-specific cuts, hand-stripping &amp; show coats — by appointment, never overbooked.",
        "services_intro": "Bath, brush, cut, style, nails, ears, teeth — we handle it all. Small-shop attention, no kennels, no rushing.",
        "services": [
            ("🐕","Full Grooming","Bath, brush-out, breed-specific cut, ear cleaning, nail trim, sanitary trim. 1-2 hour appointments."),
            ("✂️","Specialty Cuts","Hand-stripping, show-coat maintenance, double-coat de-shedding, poodle scissor work."),
            ("🚿","Bath &amp; Tidy","Wash, blow-dry, brush-out, nails &amp; ears. No haircut, no fuss. Perfect between full grooms."),
            ("🐾","Nail Care","Nail trim, dremel grind &amp; pad work. By appointment or walk-in, $15."),
            ("🦴","Dog Walking","30-min &amp; 60-min walks. Drop-ins, pack walks, weekend coverage. Bonded &amp; insured."),
            ("🏠","Pet Sitting","Daily check-ins, overnight stays, vacation care. Treats, pills, &amp; cuddles included."),
        ],
        "reviews": [
            ("My golden retriever HATES the groomer — except this one. She comes home calm, clean, smelling great, and her cut is always perfect. Best in the area, hands down.","S. Mitchell","Loyal Customer"),
            ("Used the dog walking service for a year now — reliable, professional, and our pup actually waits at the window for them. Gold-standard service.","K. Holland","Walking Customer"),
            ("Hand-stripping my standard schnauzer is a lost art and they nail it every time. Show-quality work, fair price, kind to my dog.","R. Martinez","Show Coat Customer"),
        ],
        "hero_imgs": ["1587300003388-59208cc962cb","1601758228041-f3b2795255f1","1583511655857-d19b40a7a54e"],
        "gallery_imgs": ["1587300003388-59208cc962cb","1601758228041-f3b2795255f1","1583511655857-d19b40a7a54e","1518155317743-a8ff43ea6a5f","1576201836106-db1758fd1c97","1546491764-67a5b8bba6f9"],
        "license": "Licensed, Bonded &amp; Insured",
        "biz_blurb": "Small, quiet shop run by people who actually love dogs. By appointment only, never overbooked, every pet gets one-on-one attention.",
    },
    "cleaning": {
        "title": "Cleaning Services",
        "unit": "Homes Cleaned",
        "keywords": "house cleaning, home cleaning, deep cleaning, move-in cleaning, recurring cleaning, commercial cleaning",
        "hero_words": ("Clean home. ","Free weekend."),
        "tagline": "Top-to-bottom house cleaning from a small local crew. Same person every visit, real attention to detail, every job back-checked before we leave.",
        "services_intro": "Weekly, biweekly, monthly, deep clean, or one-time. Set a recurring schedule and reclaim your weekends.",
        "services": [
            ("🧹","Recurring Clean","Weekly, biweekly, or monthly. Same crew, same time, same checklist. Set it and forget it."),
            ("✨","Deep Clean","Top-to-bottom reset. Inside-the-oven, behind appliances, baseboards, blinds, fans &amp; vents. Every 6-12 months."),
            ("📦","Move-In / Move-Out","Empty house, full clean. Cabinets, drawers, fridge, oven, every corner. Deposit-ready or new-home ready."),
            ("🪟","Windows","Inside &amp; outside, screen wash &amp; sill detail. Add-on to deep clean or stand-alone."),
            ("🏢","Commercial","Offices, retail, after-hours scheduled cleaning. Janitorial &amp; periodic deep work."),
            ("🦠","Post-Construction","Drywall dust, paint splatter, finish-line clean. We come after the trades to deliver a move-in-ready home."),
        ],
        "reviews": [
            ("I&apos;ve tried four different cleaning services. This is the only one I trust. Same person every visit, gets the corners no one else gets, and my house actually smells clean — not like chemical fumes.","L. Davis","Recurring Customer"),
            ("Hired them for a move-out clean on a tight deadline. Crew showed up on time, knocked it out in 6 hours, place was deposit-ready. Got my full deposit back.","T. Brooks","Move-Out Customer"),
            ("Deep clean on a 3,000 sqft house — they were here all day and went home tired. Worth every dollar. House looks like new.","J. Williams","Deep Clean Customer"),
        ],
        "hero_imgs": ["1584622650111-993a426fbf0a","1581578731548-c64695cc6952","1556909114-f6e7ad7d3136"],
        "gallery_imgs": ["1584622650111-993a426fbf0a","1581578731548-c64695cc6952","1556909114-f6e7ad7d3136","1564540583246-934409427776","1597149959410-d4e3b2c0d999","1586023492125-27b2c045efd7"],
        "license": "Licensed, Bonded &amp; Insured",
        "biz_blurb": "Small, local crew. Same person every visit. We back-check every job before we leave so nothing slips. Free quote in 60 seconds &mdash; just text us photos of the rooms.",
    },
    "landscaping": {
        "title": "Landscaping &amp; Lawn Care",
        "unit": "Yards Maintained",
        "keywords": "landscaping, lawn care, hardscaping, garden design, irrigation, sprinkler, paver",
        "hero_words": ("Sharper edges. ","Greener grass."),
        "tagline": "Full-service lawn care, garden design, hardscape &amp; irrigation. Local crew, no subcontracts, every yard treated like the front of our own house.",
        "services_intro": "Mowing &amp; maintenance, paver patios, retaining walls, sprinkler systems, planting &amp; seasonal cleanup &mdash; all under one roof.",
        "services": [
            ("🌱","Lawn Maintenance","Mow, edge, trim, blow. Weekly, biweekly &amp; monthly. Same crew every visit."),
            ("🌷","Garden Design","Plant selection, beds, mulch, accent rocks, tree work. Designed for your light, soil, &amp; lifestyle."),
            ("🧱","Hardscaping","Paver patios, walkways, retaining walls, fire pits, outdoor kitchens. Built to last decades."),
            ("💧","Irrigation","Sprinkler installation, repair, controller upgrades, drip lines &amp; backflow. Save water, kill brown spots."),
            ("🍂","Seasonal Cleanup","Spring &amp; fall full-yard cleanup. Leaves, dead beds, gutters, hauling &amp; disposal. Done in a day."),
            ("🪴","Planting &amp; Sod","Tree planting, sod laying, seeding, fertilization. We plant it, we&apos;ll maintain it."),
        ],
        "reviews": [
            ("Did a full backyard reno &mdash; paver patio, retaining wall, new sod, sprinklers &mdash; in three weeks. Quality is incredible, crew was friendly, and we&apos;re using them for weekly maintenance now.","G. Anderson","Landscape Reno Customer"),
            ("Best lawn crew in town. Always on time, mow lines are crisp, edge work is perfect. My neighbors keep asking who I use.","P. Thompson","Maintenance Customer"),
            ("Sprinkler system was on its last leg &mdash; they came out, diagnosed, replaced 4 zones &amp; the controller in a day. Fixed leaks I didn&apos;t even know about. Lawn looks perfect now.","B. Walker","Irrigation Customer"),
        ],
        "hero_imgs": ["1558904541-efa843a96f01","1416879595882-3373a0480b5b","1599666499726-3aeed5a06c91"],
        "gallery_imgs": ["1558904541-efa843a96f01","1416879595882-3373a0480b5b","1599666499726-3aeed5a06c91","1564540583246-934409427776","1572125675722-238a4f1f8ea2","1598901986906-5a6c2d2b73e7"],
        "license": "Licensed, Bonded &amp; Insured",
        "biz_blurb": "Local crew, no subcontracts, every yard treated like ours. Free quote &mdash; we&apos;ll walk the property with you and email a written scope within 24 hours.",
    },
    "barber": {
        "title": "Barbershop &amp; Salon",
        "unit": "Cuts Per Year",
        "keywords": "barbershop, haircut, fade, beard trim, kids haircut, straight razor shave, men's grooming",
        "hero_words": ("Sharp cut. ","Cleaner walk-out."),
        "tagline": "Old-school barbershop in the heart of town. Skin fades, beard work, hot-towel shaves, kids&apos; cuts &mdash; every chair gets the same attention.",
        "services_intro": "Walk-ins welcome, appointments preferred. Five chairs, all licensed, all sharp.",
        "services": [
            ("💈","Haircut","Skin fade, taper fade, scissor cut, classic, kids' — every length and style. Hot towel finish."),
            ("🧔","Beard Trim &amp; Shape","Lined up, scissor work, straight-razor edges. Beard oil &amp; balm finish."),
            ("🪒","Hot Towel Shave","Full straight-razor shave with hot towel prep, premium lather &amp; aftershave. The full ritual."),
            ("👦","Kids Cuts","Quiet chair, friendly barbers, no rush. Their first haircut or every time after."),
            ("✂️","Combo Service","Cut + beard + shave in one chair. Save 15% on the bundle."),
            ("💇","Color &amp; Style","Salon services for those that want them &mdash; color, perms, blow-outs &amp; styling. Booked appointments only."),
        ],
        "reviews": [
            ("Best fade I&apos;ve had in 10 years and I&apos;ve been to every shop in town. Sharp, clean, fast, fair price. Found my barber.","D. Coleman","Loyal Customer"),
            ("Took my 4-year-old for his first haircut &mdash; they were patient, kind, gave him a sticker, and the cut looks great. Family barbershop for sure.","K. Reyes","Family Customer"),
            ("Hot towel shave is a 35-minute ritual and worth every minute. Walked out feeling like a million bucks. Going back monthly.","J. Mathis","Shave Customer"),
        ],
        "hero_imgs": ["1503951914875-452162b0f3f1","1599351431202-1e0f0137899a","1521590832167-7bcbfaa6381f"],
        "gallery_imgs": ["1503951914875-452162b0f3f1","1599351431202-1e0f0137899a","1521590832167-7bcbfaa6381f","1622286342621-4bd786c2447c","1622287162716-f311baa1a2b8","1505740106531-4243f3831c78"],
        "license": "Licensed Barbers",
        "biz_blurb": "Walk-ins welcome, appointments preferred. Five chairs, all licensed, all sharp. Old-school grooming with a clean modern shop.",
    },
}
